- package.json
- src/checkbox-table/checkbox-table.test.tsx
- src/checkbox-table/checkbox-table.tsx
- src/options-slider/options-slider.less
- src/options-slider/options-slider.test.tsx
- src/options-slider/options-slider.tsx
- src/textarea/textarea.less
- src/textarea/textarea.test.tsx
- src/textarea/textarea.tsx
- src/toggle/toggle.less
- src/toggle/toggle.tsx
- src/two-box-multiselect/two-box-multiselect.less
- src/two-box-multiselect/two-box-multiselect.test.tsx
- src/two-box-multiselect/two-box-multiselect.tsx
Extends API for certain sets of components with `disabled` property.
> Disabled states

- package-lock.json
- src/select/select.less
- src/select/select.test.tsx
- src/select/select.tsx
Adds filter functionality to the existing select component. It can be configured with optional `searchable` flag.
> Add filter functionality to the select component

- package-lock.json
- package.json
- src/form/form.tsx
Use latest received violations passed from outside.
> Set violations from props

- src/select/select.test.tsx
- src/select/select.tsx
> Adds disabled functionality for Select component on item level

- package-lock.json
- src/table/table-top.tsx
- src/table/table.less
- src/table/table.test.tsx
- src/table/table.tsx
P.S since we recently introduced Prettier some non-related things to this PR could be visible in diff.It's just formatting, nothing to worry about.
> New pagination layout and `rowsText` prop

- package.json
- src/topbar/topbar.less
- src/topbar/topbar.tsx
> Notification icon badge

- package.json
- src/topbar/topbar.less
- src/topbar/topbar.tsx
> Provide style for selected menu icon

- package-lock.json
- src/button/button.less
- src/checkbox-table/checkbox-table.test.tsx
- src/dialog/dialog.tsx
- src/form/form-group.less
- src/form/form-group.tsx
- src/form/form-validation.test.tsx
- src/form/form-validation.ts
- src/form/form.less
- src/form/form.test.tsx
- src/form/form.tsx
- src/input/input.less
- src/options-slider/options-slider.test.tsx
- src/radio-group/radio-group.less
- src/radio-group/radio-group.tsx
- src/select/select.less
- src/select/select.test.tsx
- src/select/select.tsx
- src/textarea/textarea.test.tsx
- src/topbar/dropdown.tsx
- src/topbar/topbar.tsx
- src/variables.less
Prettier applied some formatting, so that thing is in the diff as well.
> Form updates + other components (radio-group, button)

- package-lock.json
- package.json
- src/form/form-group.less
- src/form/form-group.tsx
- src/icons.less
Minor form changes.
lodash version is also bumped up, because of security vulnerability.
> Form fixes

- package-lock.json
- src/checkbox-table/checkbox-table.less
- src/checkbox-table/checkbox-table.test.tsx
- src/checkbox-table/checkbox-table.tsx
- src/checkbox/checkbox.less
- src/checkbox/checkbox.tsx
- src/form/form.less
- src/index.less
- src/multi-level-checkbox-editor/multi-level-checkbox-editor.less
- src/multi-level-checkbox-editor/multi-level-checkbox-editor.test.tsx
- src/multi-level-checkbox-editor/multi-level-checkbox-editor.tsx
- src/multi-level-checkbox-editor/node-box.tsx
- src/multi-level-checkbox-editor/tri-state-checkbox.tsx
- src/two-box-multiselect/two-box-multiselect.less
- src/two-box-multiselect/two-box-multiselect.tsx
Mostly visual updates.Affected components are:
- Checkbox
- Multi Level Checkbox Editor
- Two Box Multiselect
> Components update

- package-lock.json
- package.json
- src/multi-level-checkbox-editor/multi-level-checkbox-editor.less
- src/multi-level-checkbox-editor/multi-level-checkbox-editor.tsx
I had to lock version of the rc-slider because newer version breaks CSS.
> Bugfixes and rc-slider version downgrade

- package-lock.json
- package.json
- src/icons.less
- src/multi-level-checkbox-editor/multi-level-checkbox-editor.less
- src/multi-level-checkbox-editor/multi-level-checkbox-editor.test.tsx
- src/multi-level-checkbox-editor/multi-level-checkbox-editor.tsx
- src/multi-level-checkbox-editor/search-input.less
- src/multi-level-checkbox-editor/search-input.test.tsx
- src/multi-level-checkbox-editor/search-input.tsx
Besides search functionality, this PR introduces 2 types of placeholder texts:
- Explanatory text when search gives some result
- Text that informs user that there are no data available atm
> Multi Level Checkbox Editor with search

- src/dialog/dialog.less
- src/dialog/dialog.test.tsx
- src/dialog/dialog.tsx
I've changed the Dialog according to the new requirements.
Normal Screen
Responsive
> Change the dialog layout and styling

- package-lock.json
- src/select/select.less
- src/select/select.test.tsx
- src/select/select.tsx
- CSS Update
- Clear search input on click outside
> Select Component updates

- src/button/button.less
- src/spinner/spinner.less
- src/topbar/navigation-items.less
- src/topbar/topbar.less
- src/tree/tree.less
- src/variables.less
> Update base colors

- src/dialog/dialog.less
According to UI/UX designer we got new changes and here we are.
> Change dialog styling

- package.json
- src/tooltip/tooltip.less
Sizes are measured according to variables.
> Tooltip convert sizes based on variables

- src/form/form.test.tsx
- src/form/form.tsx
to initially open certain groups
> Adds optional `expandedGroupIds` prop to `Form` component 

- src/tree/node.test.tsx
- src/tree/node.tsx
- src/tree/tree.less
Provides the disabled behaviour for a sidebar node. Optional disableMessage shown as a Tooltip to the user.
> ANALYTICS-2214 : Provide disable feature for the sidebar node

- package.json
- src/index.less
- src/index.ts
- src/message-box/index.tsx
- src/message-box/message-box.less
- src/message-box/message-box.test.tsx
- src/message-box/message-box.tsx
- src/variables.less
Due to lacking specs only implemented for `SeverityLevel.INFO`
> Adds implementation for MessageBox component

- package.json
- src/input/password-input.test.tsx
- src/input/password-input.tsx
Provided a new boolean flag to disable the AutoComplete feature of the PasswordInput.
> Password input autocomplete disable functionality

- package.json
- src/input/input.test.tsx
- src/input/input.tsx
- src/input/password-input.test.tsx
Provide optional autocomplete behavior for the input component. Auto-complete feature is enabled by default.
> Configurable autocomplete feature for the input component

- package.json
- src/button/button.less
This requirement was again changed
> modify border radius
